begin;
select plan(10);
set local role anon;
select throws_ok('select * from public.leads', '42501', 'permission denied for table leads', 'anonymous cannot read leads');
select throws_ok($$select public.lead_receipt('034d5a73-7631-467f-8e07-0e0b68636592', repeat('a',64))$$, '42501', 'permission denied for function lead_receipt', 'anonymous cannot probe receipts');
reset role;
set local role authenticated;
select is((select count(*) from public.leads), 0::bigint, 'unprivileged users see no leads');
select throws_ok($$insert into public.leads(name) values('injected')$$, '42501', 'permission denied for table leads', 'authenticated cannot insert');
reset role;
set local role service_role;
select is(public.submit_lead('034d5a73-7631-467f-8e07-0e0b68636592', repeat('a',64), '{"name":"Ada","contact":"a@example.com","operator":"Yurt","beds":120,"city":"İstanbul","language":"tr","message":""}', gen_random_uuid()), 'accepted', 'server persists valid lead');
select is(public.submit_lead('034d5a73-7631-467f-8e07-0e0b68636592', repeat('a',64), '{"name":"Ada","contact":"a@example.com","operator":"Yurt","beds":120,"city":"İstanbul","language":"tr","message":""}', gen_random_uuid()), 'accepted', 'duplicate returns receipt');
select is((select count(*) from public.leads), 1::bigint, 'duplicate does not insert twice');
select is(public.lead_receipt('034d5a73-7631-467f-8e07-0e0b68636592', repeat('b',64)), 'conflict', 'key cannot change data');
select ok((select bool_and(allowed = (attempt <= 10)) from (select n attempt, public.consume_lead_rate(repeat('c',64)) allowed from generate_series(1,11) n) attempts), 'eleventh attempt is rate limited');
reset role;
set local role authenticated;
select is((select count(*) from public.leads), 0::bigint, 'unprivileged users cannot see the persisted lead');
reset role;
select * from finish();
rollback;
