export const announcementCopy = {
  en: {
    revise: "Publish new revision",
    revisionOf: "Announcement to revise",
    chooseRevision: "Choose a published announcement",
    reviseHint:
      "Enter the complete revised message, translations and audience. Publishing a revision requires every active recipient to acknowledge it again.",
    history: "Revision history and follow-up",
    export: "Export CSV",
    all: "All recipients",
    filter: "Filter",
    recipient: "Recipient",
    resolved: "Recipient resolved at",
    title: "Announcements",
    draft: "Save draft",
    publish: "Publish",
    archive: "Archive",
    acknowledge: "I acknowledge this announcement",
    acknowledged: "Acknowledged",
    unacknowledged: "Awaiting acknowledgment",
    inactive: "Inactive recipients",
    empty: "No announcements to show.",
    error:
      "The action could not be completed. Check your access and try again.",
    saved: "Saved.",
    scope: "Audience",
    operator: "Entire Operator",
    branches: "Selected Branches",
    source: "Source language",
    content: "Source message",
    translations: "Optional human translations",
    fallback: "Translation unavailable. Displaying",
    manage: "Manage announcements",
    tr: "Turkish",
    en: "English",
    ar: "Arabic",
    published: "Published",
    archived: "Archived",
    draftStatus: "Draft",
  },
  tr: {
    revise: "Yeni revizyonu yayınla",
    revisionOf: "Güncellenecek duyuru",
    chooseRevision: "Yayınlanmış duyuru seçin",
    reviseHint:
      "Güncel iletinin tamamını, çevirileri ve hedef kitleyi girin. Yeni revizyonda aktif alıcıların yeniden onaylaması gerekir.",
    history: "Revizyon geçmişi ve takip",
    export: "CSV dışa aktar",
    all: "Tüm alıcılar",
    filter: "Filtrele",
    recipient: "Alıcı",
    resolved: "Alıcı belirleme zamanı",
    title: "Duyurular",
    draft: "Taslağı kaydet",
    publish: "Yayınla",
    archive: "Arşivle",
    acknowledge: "Bu duyuruyu onaylıyorum",
    acknowledged: "Onaylandı",
    unacknowledged: "Onay bekleniyor",
    inactive: "Etkin olmayan alıcılar",
    empty: "Gösterilecek duyuru yok.",
    error: "İşlem tamamlanamadı. Yetkinizi kontrol edip tekrar deneyin.",
    saved: "Kaydedildi.",
    scope: "Hedef kitle",
    operator: "Tüm işletme",
    branches: "Seçili şubeler",
    source: "Kaynak dil",
    content: "Kaynak ileti",
    translations: "İsteğe bağlı insan çevirileri",
    fallback: "Çeviri yok. Gösterilen dil",
    manage: "Duyuruları yönet",
    tr: "Türkçe",
    en: "İngilizce",
    ar: "Arapça",
    published: "Yayınlandı",
    archived: "Arşivlendi",
    draftStatus: "Taslak",
  },
  ar: {
    revise: "نشر إصدار جديد",
    revisionOf: "الإعلان المراد تعديله",
    chooseRevision: "اختر إعلانًا منشورًا",
    reviseHint:
      "أدخل الرسالة المعدلة كاملة والترجمات والجمهور. يجب على المستلمين النشطين الإقرار بالإصدار الجديد مجددًا.",
    history: "سجل الإصدارات والمتابعة",
    export: "تصدير CSV",
    all: "جميع المستلمين",
    filter: "تصفية",
    recipient: "المستلم",
    resolved: "وقت تحديد المستلم",
    title: "الإعلانات",
    draft: "حفظ المسودة",
    publish: "نشر",
    archive: "أرشفة",
    acknowledge: "أقر بالاطلاع على هذا الإعلان",
    acknowledged: "تم الإقرار",
    unacknowledged: "بانتظار الإقرار",
    inactive: "مستلمون غير نشطين",
    empty: "لا توجد إعلانات لعرضها.",
    error: "تعذر إكمال الإجراء. تحقق من صلاحياتك وحاول مجددًا.",
    saved: "تم الحفظ.",
    scope: "الجمهور",
    operator: "جميع فروع المشغل",
    branches: "فروع محددة",
    source: "لغة المصدر",
    content: "الرسالة الأصلية",
    translations: "ترجمات بشرية اختيارية",
    fallback: "الترجمة غير متاحة. اللغة المعروضة",
    manage: "إدارة الإعلانات",
    tr: "التركية",
    en: "الإنجليزية",
    ar: "العربية",
    published: "منشور",
    archived: "مؤرشف",
    draftStatus: "مسودة",
  },
} as const;
